### PR TITLE
fix: reroute 'Know more' to events

### LINKED ISSUE #85: Fix know more
image

redirect know more to /events

### PR DESCRIPTION
**Pull request by AdityaGupta0001**
# Description

- Rerouted 'Know-more' on the home page to the events page
- The "Know more" button in the home page
image

- Redirected to Events page
image

- Fixes #85 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by utkarshini14 — COMMENTED** [review]
@AdityaGupta0001 use proper commits. No past tense.

**Review by utkarshini14 — CHANGES_REQUESTED** [review]
also upload image of the changes implemented

File: shared/components/home/card.tsx [hunk 1]
```diff
@@ -23,11 +24,11 @@ const HomeCard = (props: {
       </h1>
       <p className="text-white font-light px-3 mt-3 text-xs">{props.desc}</p>
       <div className="text-center mt-10 mb-5">
-        <a href={`${props.link}`} target="_blank" rel="noopener noreferrer">
+        <Link href={`/events`}>
           <button className="bg-black border rounded-full text-white text-xs px-5 py-1 border-white focus:outline-none">
             Know More
           </button>
-        </a>
+        </Link>
```
Comment (utkarshini14) [inline shared/components/home/card.tsx:31]: also @AdityaGupta0001 why did you use Link instead of a tag?

Comment (AdityaGupta0001) [reply shared/components/home/card.tsx:31]: Since we don't need to refresh the page everytime the user clicks "Know more" we use Link tag to just redirect to another page of the website.

Comment (shawshankkumar) [reply shared/components/home/card.tsx:31]: Great answer @AdityaGupta0001

Comment (shawshankkumar) [reply shared/components/home/card.tsx:31]: Do the rest of the fixes please @AdityaGupta0001

Comment (AdityaGupta0001) [reply shared/components/home/card.tsx:31]: Done the changes @utkarshini14

Comment (shawshankkumar) [reply shared/components/home/card.tsx:31]: image

@AdityaGupta0001 you have to click on request review again everytime you make the changes, the little circle button

File: shared/components/home/card.tsx [hunk 2]
```diff
@@ -1,4 +1,5 @@
 import { motion } from 'framer-motion'
+import Link from 'next/dist/client/link'
```
Comment (shawshankkumar) [inline shared/components/home/card.tsx:2]: @AdityaGupta0001 why are you importing the changes from next/dist/client/link? did you try next/link? https://nextjs.org/docs/pages/api-reference/components/link

**Review by shawshankkumar — COMMENTED** [review]
?

File: shared/components/home/card.tsx (hunk 2 above)
Comment (AdityaGupta0001) [reply shared/components/home/card.tsx:2]: So sorry bhaiya, actually I just directly used Link tag and it automatically imported it as next/dist/client/link. Ill fix it now.

File: shared/components/home/card.tsx (hunk 1 above)
Comment (AdityaGupta0001) [reply shared/components/home/card.tsx]: Done

File: shared/components/home/card.tsx (hunk 2 above)
Comment (AdityaGupta0001) [reply shared/components/home/card.tsx]: Done bhaiya

**Review by sm-sami — APPROVED** [review]

**Review by utkarshini14 — APPROVED** [review]
looks good!

**Review by shawshankkumar — APPROVED** [review]
LGTM 🚀
